console: Add configurable newline command and RETURN key behavior
bgomberg/anchor pull request #3
Opened 2023-05-15 16:28 UTC by vmk94

To address compatibility issues with popular serial console applications like PuTTY, this commit introduces a configurable parameter in the source code. Previously, the console code used '\n' for newline output and expected '\n' as input to move to the beginning of a new line. However, PuTTY sends '\r' (Carriage Return) when the RETURN key is pressed and expects "\r\n" to move the cursor to the beginning of a new line. With this update, the newline command and the behavior of the RETURN key can be customized to ensure compatibility with PuTTY and similar applications.

2023-08-10 00:47 UTC, bgomberg requested changes
Thanks for the PR and my apologies for the delay in getting to this.

I'd be happy to merge this, but would want to keep the default configuration matching the current behavior as to not break any existing users. Could you please update the default values in `console_config.h` accordingly? Also, if you could add a short blurb documenting these new options to the "Compile Options" section of `console/README.md` that would be much appreciated.

2023-10-31 16:46 UTC, vmk94 commented
Thank you for your comments. I made the changes as requested.

2023-11-01 21:15 UTC, bgomberg approved these changes

2023-11-01 21:16 UTC, merged

2023-11-01 21:16 UTC, bgomberg commented
Merged. Thanks!